# Generated by Django 6.0.4 on 2026-05-07 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('medical_records', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='file_type',
            field=models.CharField(choices=[('report', 'Medical Report'), ('xray', 'X-Ray'), ('ultrasound', 'Ultrasound'), ('bloodtest', 'Blood Test'), ('prescription', 'Prescription'), ('image', 'Image'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='uploaded_by_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_records', to='doctors.doctorprofile'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='uploaded_by_patient',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patientprofile'),
        ),
    ]
