# Generated by Django 6.0.4 on 2026-05-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_medicalrecord_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='from_info',
            field=models.CharField(default='Unknown', help_text='Sender of the report', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='to_info',
            field=models.CharField(default='Unknown', help_text='Recipient of the report', max_length=255),
            preserve_default=False,
        ),
    ]
