# Generated by Django 6.0.4 on 2026-05-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
