# Generated by Django 6.0.4 on 2026-05-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctorprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
