# Generated by Django 6.0.4 on 2026-05-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctorprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='rating',
            field=models.FloatField(default=4.5),
        ),
    ]
