# Generated by Django 6.0.4 on 2026-05-12 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('doctors', '0002_doctorprofile_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department'),
        ),
    ]
