# Generated by Django 6.0.4 on 2026-06-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_doctorprofile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='doctor_id',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True),
        ),
    ]
