# Generated by Django 6.0.4 on 2026-05-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_type',
            field=models.CharField(choices=[('video', 'Video Call'), ('audio', 'Audio Call'), ('discussion', 'Discussions & Suggestions'), ('in_person', 'In-Person Consultation')], default='in_person', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
