# Generated by Django 6.0.4 on 2026-05-21 07:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_alter_patientprofile_age_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('symptom', 'Symptom'), ('disease', 'Disease'), ('medicine', 'Medicine'), ('conversation', 'Conversation')], max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('source', models.CharField(default='manual', max_length=100)),
                ('language', models.CharField(default='en', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('symptom', 'Symptom Model'), ('disease', 'Disease Model'), ('risk', 'Risk Model')], max_length=50)),
                ('file_path', models.CharField(max_length=500)),
                ('accuracy', models.FloatField(default=0.0)),
                ('precision_score', models.FloatField(default=0.0)),
                ('recall_score', models.FloatField(default=0.0)),
                ('version', models.IntegerField(default=1)),
                ('training_samples', models.IntegerField(default=0)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('te', 'Telugu')], default='en', max_length=5)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('extracted_symptoms', models.JSONField(blank=True, default=list)),
                ('predicted_diseases', models.JSONField(blank=True, default=list)),
                ('risk_level', models.CharField(blank=True, default='', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='patients.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=10)),
                ('content', models.TextField()),
                ('translated_content', models.TextField(blank=True, default='')),
                ('symptoms_extracted', models.JSONField(blank=True, default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.chatsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DiseasePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=200)),
                ('disease_name_te', models.CharField(blank=True, default='', max_length=200)),
                ('confidence', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('department', models.CharField(blank=True, default='', max_length=200)),
                ('recommended_action', models.TextField(blank=True, default='')),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ai_assistant.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='RetrainQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retrain_entries', to='ai_assistant.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='SymptomEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_name', models.CharField(max_length=200)),
                ('symptom_name_te', models.CharField(blank=True, default='', max_length=200)),
                ('confidence', models.FloatField(default=0.0)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_entries', to='ai_assistant.chatmessage')),
            ],
        ),
        migrations.CreateModel(
            name='WebCollectedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('symptom', 'Symptom'), ('disease', 'Disease'), ('medicine', 'Medicine'), ('treatment', 'Treatment')], default='symptom', max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.JSONField(default=dict)),
                ('category', models.CharField(choices=[('allergy', 'Allergy'), ('chronic', 'Chronic Condition'), ('medication', 'Current Medication'), ('family_history', 'Family History'), ('lifestyle', 'Lifestyle'), ('past_diagnosis', 'Past Diagnosis'), ('other', 'Other')], default='other', max_length=100)),
                ('source', models.CharField(default='chat', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_memories', to='patients.patientprofile')),
            ],
            options={
                'unique_together': {('patient', 'key')},
            },
        ),
    ]
