# Generated by Django 6.0.4 on 2026-05-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_consultation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='call_session_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('ringing', 'Ringing'), ('active', 'Active'), ('ended', 'Ended')], default='idle', max_length=20),
        ),
    ]
