# Generated by Django 6.0.4 on 2026-06-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_call_session_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
