# Generated by Django 6.0.4 on 2026-05-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('medicine', 'Medicine'), ('appointment', 'Appointment'), ('follow_up', 'Follow-up')], default='medicine', max_length=20),
        ),
    ]
