# Generated by Django 6.0.4 on 2026-05-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='blood_group',
            field=models.CharField(blank=True, default='N/A', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, default='N/A', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(blank=True, default='Not Specified', max_length=20, null=True),
        ),
    ]
