# Generated by Django 6.0.4 on 2026-05-23 16:32

import consultations.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('doctors', '0005_doctorprofile_rating'),
        ('patients', '0002_alter_patientprofile_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_seconds', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('connection_quality', models.CharField(blank=True, default='Good', max_length=50)),
                ('camera_used', models.BooleanField(default=False)),
                ('mic_used', models.BooleanField(default=False)),
                ('screen_share_used', models.BooleanField(default=False)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='consultations.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=consultations.models.get_secure_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to='consultations.consultation')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_media', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_media', to='patients.patientprofile')),
            ],
        ),
    ]
