# Generated by Django 6.0.4 on 2026-05-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('te', 'Telugu'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('kn', 'Kannada'), ('ml', 'Malayalam')], default='en', max_length=5),
        ),
    ]
