# Generated by Django 6.0.4 on 2026-06-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_chatsession_user_alter_chatsession_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='assistant_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('patient', 'Patient')], default='patient', max_length=20),
        ),
    ]
